import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { allDocMds, DocMd, allDocMdxes, DocMdx } from 'contentlayer/generated';
import ChakraUIProvider from '@/uiLayer.chakra/uiLayer.chakra.provider';
import { Box, Code, Heading, Stack, Text } from '@chakra-ui/react';
import styles from '../styles/Home.module.css';


type HomePageProps = {
  data: {
    docsMd: DocMd[];
    docsMdx: DocMdx[];
  }
}

export const getStaticProps: GetStaticProps<HomePageProps> = async () => {
  return { props: { data: { docsMd: allDocMds, docsMdx: allDocMdxes } } }
}

const Home: NextPage<HomePageProps> = ({ data }) => {
  return (
    <>
      <ContentLayerSection data={data} />
      <ChakraSection />
      <DefaultNextSection />
    </>
  );
};

export default Home;

const ContentLayerSection = ({ data }: { data: HomePageProps['data'] }) => {
  const { docsMd, docsMdx } = data;
  return (
    <>
      <div className="max-w-4xl mx-auto">

        <div className="bg-gray-100">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-2xl py-16 sm:py-24 lg:max-w-none lg:py-32">
              <h2 className="text-2xl font-bold text-gray-900">Doc Md</h2>

              <div className="mt-6 space-y-12 lg:grid lg:grid-cols-3 lg:gap-x-6 lg:space-y-0">
                {docsMd.map((doc) => (
                  <div key={doc._id} className="group relative">
                    <div className="relative h-80 w-full overflow-hidden rounded-lg bg-white group-hover:opacity-75 sm:aspect-w-2 sm:aspect-h-1 sm:h-64 lg:aspect-w-1 lg:aspect-h-1">
                      {/* <img
                        src={callout.imageSrc}
                        alt={callout.imageAlt}
                        className="h-full w-full object-cover object-center"
                      /> */}
                    </div>
                    <h3 className="mt-6 text-sm text-gray-500">
                      <Link href={doc.url}>
                        <a>
                          <span className="absolute inset-0" />
                          {doc.title}
                        </a>
                      </Link>
                    </h3>
                    <p className="text-base font-semibold text-gray-900">{doc.description}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        <div className="bg-gray-100">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-2xl py-16 sm:py-24 lg:max-w-none lg:py-32">
              <h2 className="text-2xl font-bold text-gray-900">Doc Mdx</h2>

              <div className="mt-6 space-y-12 lg:grid lg:grid-cols-3 lg:gap-x-6 lg:space-y-0">
                {docsMdx.map((doc) => (
                  <div key={doc._id} className="group relative">
                    <div className="relative h-80 w-full overflow-hidden rounded-lg bg-white group-hover:opacity-75 sm:aspect-w-2 sm:aspect-h-1 sm:h-64 lg:aspect-w-1 lg:aspect-h-1">
                      {/* <img
                        src={callout.imageSrc}
                        alt={callout.imageAlt}
                        className="h-full w-full object-cover object-center"
                      /> */}
                    </div>
                    <h3 className="mt-6 text-sm text-gray-500">
                      <Link href={doc.url}>
                        <a>
                          <span className="absolute inset-0" />
                          {doc.title}
                        </a>
                      </Link>
                    </h3>
                    <p className="text-base font-semibold text-gray-900">{doc.description}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

      </div>
    </>
  )
}

const ChakraSection = () => (
  <ChakraUIProvider>
    <Box maxW="container.sm" m="auto" py={20}>
      <Heading mb={8}>Hello From Chakra UI.</Heading>
      <Stack spacing={8}>
        <Text>Chakra Custom Theme is found in <Code>./uiLayer.chakra/uiLayer.chakra.customTheme.ts</Code>.</Text>
        <Text>An example of a layout components (mean to be used across all app) is <Code>./components/layout</Code>.</Text>
        <Text>An example of a page is in <Code>./views/Home/Home.tsx</Code>.
          <br />You can view it by rendering the component inside this next page (.index.tsx)
        </Text>
        <Text>If you will use Chakra UI in more pages, consider moving the <Code>{'<ChakraUIProvider>'}</Code> in <Code>/pages/_app.tsx</Code> or in <Code>/pages/_document.tsx</Code></Text>
      </Stack>
    </Box>
  </ChakraUIProvider>
)

const DefaultNextSection = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>

      <p className={styles.description}>
        Get started by editing{' '}
        <code className={styles.code}>pages/index.tsx</code>
      </p>

      <div className={styles.grid}>
        <a href="https://nextjs.org/docs" className={styles.card}>
          <h2>Documentation &rarr;</h2>
          <p>Find in-depth information about Next.js features and API.</p>
        </a>

        <a href="https://nextjs.org/learn" className={styles.card}>
          <h2>Learn &rarr;</h2>
          <p>Learn about Next.js in an interactive course with quizzes!</p>
        </a>

        <a
          href="https://github.com/vercel/next.js/tree/canary/examples"
          className={styles.card}
        >
          <h2>Examples &rarr;</h2>
          <p>Discover and deploy boilerplate example Next.js projects.</p>
        </a>

        <a
          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
        >
          <h2>Deploy &rarr;</h2>
          <p>
            Instantly deploy your Next.js site to a public URL with Vercel.
          </p>
        </a>
      </div>
    </main>

    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{' '}
        <span className={styles.logo}>
          <Image
            src="/vercel.svg"
            alt="Vercel Logo"
            width={72}
            height={16}
          />
        </span>
      </a>
    </footer>
  </div>

)
